#
# Settings for Drinkaccounting
#
CGROSS:
  Drinkaccounting:
    system:
      dateFormat: 'Y-m-d'
      backupPath: '/tmp/'
      mysqldumpPath: ''
      mysqlPath: ''
    statementWizard:
      steps: 7


# Language of the interface
TYPO3:
  FLOW3:
    i18n:
      defaultLocale: en
